### ISSUE TITLE
Mettre les textes en justifié pour éviter les zigzag

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#10]
Mose, 

Une dernière chose, pourrais-tu STP mettre tous les textes en justifié pour éviter les zigzags? 

Merci
Yam

**Comment by mose** [comment]
Un détail que je laisse volontiers a Shelley. :)

**Comment by mose** [comment]
Quand meme, je déconseille.

https://dmjcomputerservices.com/blog/why-you-shouldnt-align-html-justify/

**Comment by yaminasaheb** [comment]
J'entends bien ton argument Mose. Mais notre audience n'est pas forcément geek. Elle est habituée à des textes en justifiés. 
Je te remercie de faire le nécessaire et de les mettre en justifié surtout maintenant qu'on a la fonction export en PdF.

**Comment by mose** [comment]
Cet argument est irrecevable. Tous les media papier qui publient en ligne n'utilisent pas la justification des textes. L'algorythme de justification n'est juste pas bon, sur le web. En publication papier on peut jouer sur l'interlettrage, l'echelle horizontale, la sécation des mots, et plusieurs autres astuces. En web, seul l'espace entre les mots va etre utilisé pour justifier.

Le washington post, liberation, le monde, ce sont des media papier, leur cible n'est pas geek, et ils n'utilisent pas la justification des textes sur le web meme dans leur version imprimable.

En fait, c'est aux textes justifiés qu'ont reconnait les sites qui sont fait par des gens qui ne connaissent pas le web. Ca me dérange un peu d'être associé à un site qui aurait une telle reputation.

De la meme façon, on ne met jamais d'espace avant les points ou les virgules. JAMAIS. C'est une hérésie typographique.

**Comment by shelleycavaness** [comment]
Hi Yamina, I did a quick check on the web and I only found two sites that justify: both are French publishing houses: Gallimard and Hachette (both reproducing book-like format). I also looked at our maple syrup eating Canadians and the trend is the same- meaning justification is out for an entire webpage.
