### ISSUE TITLE
Exporter les textes en PdF

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#12]
Bonjour, 

Merci de prévoir une fonction d'export des textes (tous les textes, chacun séparément)  en PdF. 
Yamina

**Comment by mose** [comment]
Sur chaque post y'a un icone 'print' en haut a guache et la version imprimable peut etre sauvée en PDF.

**Comment by yaminasaheb** [comment]
Merci chef
