### ISSUE TITLE
Page d'accueil / executive summary

### ISSUE THREAD

**Issue by thanhcrazytoad** [crazy-toads/crazy-toads.github.io#13]
Salut à tous,

Shelley vient de m'expliquer l'usage de "Issues". Trop bien !

Voici donc le truc. La page d'accueil actuelle n'est pas à jour, car elle date d'avril et entre-temps, on a fini (ouf !) le manuscrit, qui est parti en presse.

J'ai donc repris le fil conducteur du Manifeste (qui fait 20 pages+) et l'ai compacté dans le doc suivant, avec les crobars et les liens avec les pages existantes du site surlignées en jaune
[1. Website Manifesto short.docx](https://github.com/crazy-toads/crazy-toads.github.io/files/1289964/1.Website.Manifesto.short.docx)
J'ai passé beaucoup de temps dessus mais n'ai pas réussi à le compacter davantage. Pour alléger, j'ai extrait trois textes importants, que j'ai mis dans le document suivant. L'idée serait de pouvoir mettre un cartouche "Lire la suite" qui envoie sur chacun de ces trois textes (j'ai indiqué où  cela devrait se trouver dans le texte principal)
[2. Website Manifesto more.docx](https://github.com/crazy-toads/crazy-toads.github.io/files/1289965/2.Website.Manifesto.more.docx)

Ma question c'est : est-ce que cette page d'accueil n'est pas trop lourde ? Peut-on la "replier" en faisant apparaître les titres et sous-titres ? Ou faut-il plutôt la résumer en 10 lignes et créer une page plus détaillée qui s'appellerait "Manifeste Résumé" ou "Manifeste : le contenu" ?

Cette page d'accueil est très importante, puisqu'elle articule tout le reste (Cercles, Mare à crapauds, Crapauds, Partenaires, il y aura aussi le renvoi vers le formulaire d'engagement / souscription etc), mais ce n'est peut-être pas une bonne idée de tout mettre là ? Il me semble important que le contenu complet du Manifeste soit présent et très visible dans le sommaire en tous cas.

Vos avis ?

Merci !!!

**Comment by yaminasaheb** [comment]
J'opterais pour l'idée d'une page résumé en 10 lignes avec un lien vers une page plus détaillée qui résume le Manifeste

**Comment by shelleycavaness** [comment]
Hi Thanh and Yamina, I put the executive summary online so you could get an idea of what it would look like. I know there are still modification and links to add, but I wanted you both to see what it looks like to help you better reflect on what makes sense for your needs. sometimes you need to see it live to decide ;-)

**Comment by thanhcrazytoad** [comment]
Merci Shelley,

En effet, Yamina la page est trop longue pour une page d'accueil !
Je vais écrire un blurb de 10-15 lignes pour la page d'accueil d'ici demain.
Avec  
- le WHY des crapauds fous 
- un résumé du trajet (depuis octobre 2016 à aujourd'hui) et du contenu, les bios
- nos principes et ce qui nous guide
- l'actu, avec l'appel à nous rejoindre pour "faire" crapaud fou => lien vers l'API (Shelley, t'en es où là dessus ?), le TEDx
Autre chose ?
