### ISSUE TITLE
Page Cercles et Mare à Crapauds

### ISSUE THREAD

**Issue by thanhcrazytoad** [crazy-toads/crazy-toads.github.io#14]
Pour votre info, 

ces deux pages sont en désordre par rapport au Manifeste, ça pose un problème 1) de logique pour les Cercles et 2) de lisibilité car les éléments qui ont été mis dans la Mare à Crapauds devraient se retrouver insérés dans les Cercles, dans le même ordre (pour info, voir la maquette finale du bouquin à partir de la page 121)
[CrapaudFouEO7-TN.pdf](https://github.com/crazy-toads/crazy-toads.github.io/files/1289977/CrapaudFouEO7-TN.pdf)

Shelley m'a donné qq indications pour faire les modifs dans les pages en .md. Je vais donc essayer de faire les modifs moi-même demain ou lundi.

je vous tiens au courant si je galère trop !

Merci

**Comment by yaminasaheb** [comment]
Je pense qu'il y a doublon entre la Mare à crapauds et les cercles. Je garderais une seule rubrique, celle des cercle en la nommant ''Mare à crapauds. ''
L'autres rubrique devait correspondre à un blog, je propose de la cacher pour le moment et de la rendre visible quand on aura des posts.

**Comment by thanhcrazytoad** [comment]
Il y a deux niveaux de texte concernant les Cercles dans le Manifeste
1) le niveau agrégé des Cercles & Principes, texte qui figure dans le fil conducteur du livre (Partie II - Manifeste des 34) et que j'avais en grande partie rédigé à la fin des Treilles
2) le niveau détaillé des Cercles et des encarts = texte qui a été compilé en faisant travailler tout le monde après les Treilles (Partie III - Pour aller plus loin)

=> c'est cohérent d'avoir une page Cercles & Principes qui reprend le premier texte (Shelley : pour éviter les erreurs, je te renvoie le texte qu'il faut reprendre)
[Website Cercles & Principes.docx](https://github.com/crazy-toads/crazy-toads.github.io/files/1290364/Website.Cercles.Principes.docx)
=> et ensuite garder dans "Mare à Crapauds" le deuxième texte, correspondant à la Partie III du Manifeste, qui reprend le travail effectué post-Treilles sur les Cercles et sur les encarts. 

Le problème est que ça fait beaucoup de choses dans cette Mare. J'ai donc fait un tri en repartant du sommaire 
[Architecture Mare à crapauds.docx](https://github.com/crazy-toads/crazy-toads.github.io/files/1290383/Architecture.Mare.a.crapauds.docx)
Dans ce document je propose un texte d'introduction pour la Mare, puis une architecture qui permet de replier les encarts dans les Cercles, et de montrer la manière dont ces Cercles s'articulent

Yam, t'en penses quoi ?

**Comment by yaminasaheb** [comment]
Bonne idée. Mais il faut voir ce que ça donne une fois en ligne

**Comment by thanhcrazytoad** [comment]
Ca ira Shelley pour faire tout ça ?
En cas de besoin, voici les priorités 
1) modifier la page d'accueil (cf Issue 10)+ reporter le texte existant sur une nouvelle page "Manifeste du Crapaud fou"
2) faire apparaître cette page "Manifeste du Crapaud fou" en onglet sur la gauche, avant Cercles
3) modifier la page "Cercles" avec le texte indiqué ci-dessus
4) refaire la page "Mare à Crapaud" avec l'architecture indiquée ci-dessus

... Shelley, qu'en penses tu ? jouable pour le 12 au soir ?

Merci !

**Comment by mose** [comment]
J'ai l'impression que cette demande a ete au moins partiellement satisfaite. Ouvrons un autre tiquet si il y a plus a faire.
