### ISSUE TITLE
Appliquer la même règle pour la taille des photos

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#15]
Pour info, 

Il y a encore un pb sur la taille des images, voir celle du texte des mousquetaires. 
Serait-il possible de coder ça? 
Merci
Yamina

**Comment by shelleycavaness** [comment]
Hi Yamina, I'm not sure I understand? which text exactly? the one you just uploaded last night? I didn't see an image? or is that the problem? ;-)

**Comment by shelleycavaness** [comment]
I think Mose has fixed the photos. We can re-open this issue if we see any other issues

**Comment by yaminasaheb** [comment]
Comme signalé dans ma demande, il s'agit du texte des mousquetaires sur le lien suivant 
http://crapaud-fou.org/mousquetaires/
Il y a une image que j'ai importé hier. Elle est après le 4ème paragraphe. Elle est miniscule. Merci de la mettre à la bonne taille

**Comment by mose** [comment]
Please upload a larger image. Agrandir un dessin ca va le flouter.
