### ISSUE TITLE
Pb avec les accents sur les textes ajoutés pour décrire les cercles

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#16]
Les textes décrivant les cercles ont tous un pb avec les accents. 
Merci de vérifier les textes mis en ligne après chaque update. 
Y

**Comment by shelleycavaness** [comment]
I saw the mistake on generation (sans accents!). since the catagories are auto-generated, I think i'm going to need some help. mister please do your magic 
@mose

**Comment by mose** [comment]
Les catégories ne sont pas auto-générées, elles sont auto-collectées. Suffit de mettre des accents dans chaque article de cette categorie, puis dans le fichier yaml, et voila. La magie n'existe pas!

**Comment by mose** [comment]
La page des cercles a été totatelement refaite, le probleme n'est donc plus.
