### ISSUE TITLE
Plusieurs images de crapauds se balladent dans la rubrique ''nous rejoindre''

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#17]
Sur la page ''nous rejoindre'', il y a 3 crapauds qui se baladent. 
Encore une fois, merci de vérifier les pages après chaque update

**Comment by shelleycavaness** [comment]
done

**Comment by yaminasaheb** [comment]
Idem, dans la page d'accueil, il y a 2 images du crapaud en vert. 
Merci de verifier toutes les pages et de s'assurer que l'image du crapaud n'est pas en double ou triple

**Comment by mose** [comment]
fixed.

note to @shelleycavaness : il faut ajouter la classe css "illus" aux images interieures qu'on veut faire disparaitre sur ecran large

**Comment by shelleycavaness** [comment]
got it ! merci !
