### ISSUE TITLE
Full screen occupation 

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#2]
Hi Mose, 
Can you please enlarge the occupation of the screen? Currently we have this long text in the middle and the rest is empty. 
Thanks
Yamina

**Comment by mose** [comment]
Je peux elargir un peu. Dis-moi si ca va.

**Comment by yaminasaheb** [comment]
C'est beaucoup mieux. Merci. 
Serait-il possible de mettre le logo du crapaud sur toutes les pages dans la partie qui est actuellement vide (sur la droite)? 
Merci

**Comment by mose** [comment]
Je peux mettre ca mais ca s'affichera uniquement pour les gens qui ont un tres grand ecran. Le comportement progressif fera disparaitre le logo quand l'ecran retrecit.

**Comment by yaminasaheb** [comment]
Tu peux faire un test pour que je vois ce que ça donne sur un grand et un petit écran
Merci

**Comment by mose** [comment]
J'ai mis le logo qui s'affiche si l'ecran fait plus de 1800px de large, ca meuble ...

**Comment by mose** [comment]
Pour info, le site doit s'afficher correctement sur tablette et mobile aussi, donc tester sur mobile ca peut valoir le coup.

**Comment by yaminasaheb** [comment]
ça meuble bien sur mon grand écran. 
Je ne vois pas le logo sur mon téléphone et tablette. Mais ça ne gêne pas du tout. Car dans ce cas, je ne vois plus le vide en blanc et tout s'affiche correctement
Je propose de garder le logo.

**Comment by mose** [comment]
Ok, c'esr reglé donc.
