### ISSUE TITLE
Page d'accueil

### ISSUE THREAD

**Issue by thanhcrazytoad** [crazy-toads/crazy-toads.github.io#20]
Après échange avec Yamina et Shelley

Je propose de reprendre le texte qui est actuellement sur la la page d'accueil pour le mettre sur une page "Manifeste du Crapaud fou". Il faudrait que cette page figure dans la colonne de gauche, avant Cercle et Crapauds.

Ensuite, remplacer la page d'accueil par ce texte plus court
[Homepage.docx](https://github.com/crazy-toads/crazy-toads.github.io/files/1290816/Homepage.docx)
Dedans j'ai surligné en jaune les liens vers les autres pages importantes du site. Note que "Cercles" devrait s'appeler si possible "Cercles & Principes"

Shelley, c'est OK pour toi ? C'est une page clé, ce serait top qu'on puisse voir ça demain !
Merci

**Comment by shelleycavaness** [comment]
I think its all done. 
1. Add tab in left-hand nav-bar. I called "Manifeste du Crapaud" because "Manifeste du Crapaud fou" looked ugly because it was too long.
2. replaced hompage text
3. Changed left-hand nav-bar to say "Cercles & Principes"
4. add link to Cercles & Principes in homepage per request.
5. added link to "Manifeste du Crapaud fou" in homepage text where you had specified link in text.

**Comment by thanhcrazytoad** [comment]
Dear Shelley,

Thanks a lot!!!

I am driving back to Paris, will take a closer look tonight upon arrival.

Bisoux !!!



Thanh Nghiem
about.me <https://about.me/tnghiem>

2017-09-11 15:07 GMT+02:00 shelley cavaness <notifications@github.com>:

**Comment by thanhcrazytoad** [comment]
Re

Je viens de checker la page "Cercles & Principes", ce n'est pas le bon
texte !

Tu as gardé l'ancienne page avec des lignes de code, qui donnent les liens
pêle-mêle. Alors qu'il faudrait tout simplement remplacer cette page par le
texte que je te joins à nouveau (il s'agit d'un texte à copier coller => si
j'ai bien compris; la page actuelle deviendrait donc une page en .md ?)

Même problème avec la page "Mare à crapauds". Mais c'est plus compliqué, je
t'appelle pour en parler plus tard.

Il y a aussi des liens qui manquent / quelques erreurs dans la page
d'Accueil, et la première ligne mise en exergue n'est pas la bonne. Je te
fais un mail dans un 2° temps

Merci !


Thanh Nghiem
about.me <https://about.me/tnghiem>

2017-09-11 15:07 GMT+02:00 shelley cavaness <notifications@github.com>:

**Comment by thanhcrazytoad** [comment]
Salut Shelley

Je viens de faire qq modifs sur la page d'accueil, et inséré qq liens.

Je ne trouve pas le lien à recopier pour envoyer vers la page "Mare à
Crapauds" , tu pourras corriger ?

Merci !

Thanh Nghiem
about.me <https://about.me/tnghiem>

Le 11 septembre 2017 à 17:33, Thanh Nghiem <thanh.nghiem101@gmail.com> a
écrit :

**Comment by thanhcrazytoad** [comment]
Encore des demandes

Est-il possible de réduire la taille de l'image de mon TED sur YouTube ? 
J'ai cherché sur le net, ça a l'air compliqué en markdown, cf https://codedump.io/share/5Nb7oW9wzvYR/1/how-to-link-an-image-in-markdown-and-also-resize-the-image

Est-il possible aussi de mettre le lien vers la page Cercles & Principes (pas trouvé son nom dans l'index) ?

Merci !

**Comment by mose** [comment]
Mais non c'est pas compliqué. J'ai arrangé ca et aussi mis le texte-image de cedric que t'as essayé d'inserer sans succès plus tot.

**Comment by thanhcrazytoad** [comment]
génial

merci, je vois le code :-)

Thanh Nghiem
about.me <https://about.me/tnghiem>

2017-09-12 22:55 GMT+02:00 Mose <notifications@github.com>:
