### ISSUE TITLE
correction url  http://crapaud-fou.org/neurodivegrence/

### ISSUE THREAD

**Issue by shelleycavaness** [crazy-toads/crazy-toads.github.io#24]
salut mose, 
la lettre 'R" est mal placé. je pensais que le ficher était mal écrit mais ce n'est pas le cas. _posts/2017-09-12-neurodivergence.md. donc j'ai regardé le ymal et j'ai vu ceci-  slug: "neurodivegrence". donc pour corriger ça suffit de modifier le yaml dans ce cas? merci mose

**Comment by mose** [comment]
fixed :)
