### ISSUE TITLE
Non pas 3 tsunamis mais au moins 4

### ISSUE THREAD

**Issue by fvanderbiest** [crazy-toads/crazy-toads.github.io#27]
Sur https://github.com/crazy-toads/crazy-toads.github.io/blob/master/pages/manifeste_du_crapaud.md#1-pas-1-mais-3-tsunamis : aucune mention de la fin probablement rapide de l'énergie abondante et peu chère...

**Comment by fvanderbiest** [comment]
Recommended reading: www.seuil.com/ouvrage/comment-tout-peut-s-effondrer-pablo-servigne/9782021223316

**Comment by mose** [comment]
Le mieux c'est de poster sur https://idees.crapaud-fou.org parce que les humains normaux ne viennent pas trop par ici.
