### ISSUE TITLE
Replacing ''Textes'' by ''Cercle de Réflexion'' and modifiying the structure

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#3]
Mose, 

Can you please replace ''Textes'' by ''Cercle de Réflexion'' or let me know how to do that? 
It terms of structure of ''Cercles de réflexion'', we should see from the menu all the cercles. 
Under each cercle, we will have a short summary (one of the text your already uploaded) and several texts. 
For the time being, we have a summary for each cercle and we have at least one additional text writtent by one of the toads. 
Thanks

**Comment by mose** [comment]
Pour info le sidebar se trouve dans `_config.yml`, on utilise `_devconfig.yml` pour le dev en local, donc il faut le changer dans les deux.

**Comment by mose** [comment]
Sinon, a propos des Textes, c'est le fil de publication de type blog, qui permet d'avoir les articles tous cercles confondus en ordre chronologique, y compris les articles qui ne sont dans aucun cercle. Mais je pense qu'il soit possible que tous les posts puissent etre qualifiés, il faudrait juste les mettre dans les bonnes `categories`.

Tu peux ajouter les descriptions pour les cercles dans un fichier `_data/cercles` et je marrangerai pour que l'affichage des cercles se fasse dans le sidebar, et que les descriptions par cercles s'affichent sous chaque cercle dans la page https://crazy-toads.github.io/cercles/ (que je viens de realiser j'avais oublié d'ajouter dans le menu).

**Comment by yaminasaheb** [comment]
Ok.
