### ISSUE TITLE
Creating links between profiles of the toads and their texts

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#4]
Mose, 
Can you please offer us the possibility to create links between profiles of the toads and their texts. 
If you look for example to Jean-Baptiste de Foucault, he has a bio and he also has a text. We should be able to go from one to another. 
Thanks
Yamina

**Comment by mose** [comment]
Ca serait pas mal, je vais laisser celui-la a Shelley, tiens.

**Comment by yaminasaheb** [comment]
Serait-il possible d'avoir cette fonctionnalité pour dimanche. Je dois partager le lien avec les crapauds lundi prochain pour avoir leur feedback et faire les modifications avant le 12/09

**Comment by mose** [comment]
Okay, du coup je m'en charge.

**Comment by mose** [comment]
Les liens sont faits, des posts vers les auteurs, et en bas de chaaque page de crapaud y'a la liste de ses posts.
