### ISSUE TITLE
Merging Textes and Cercles

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#5]
Mose, 

Les textes doivent être dans les cercles, sinon ça fera doublon. 
Je pense qu'il vaut mieux supprimer la rubrique ''textes'' et garder juste la rubrique ''cercles'' et c'est la dedans que tous les textes devraient aller. 

Si tu as conçu ''textes'' comme un blog. Alors, je pense que le mieux serait de remplacer l'intitulé ''textes'' par blog et y faire apparaître le dernier ''post'' qu'on mettra en ligne. Sachant que ce dernier post devra aussi aller dans l'un des cercles. 

Merci de me dire ce que t'en penses
Y

**Comment by mose** [comment]
Donc si je change juste `Textes` par `Blog` sans rien changer d'autre ca fait l'affaire ?

**Comment by mose** [comment]
Ca vaudrait le coup de dater les textes qui ont deja ete inclus. Si on a pas la date on peut mettre celle des rencontres des treilles, mais ca permet de garder une chronologie.

**Comment by yaminasaheb** [comment]
Oui, ça fait l'affaire. Je me charge de faire le nettoyage aprés

**Comment by yaminasaheb** [comment]
Oui, il faut dater les textes. 
Mais pour commencer tous les textes vont être à la même date (12/09). Est ce que ça va être un problème?

**Comment by mose** [comment]
Non aucun probleme, il y a juste un seul texte qui a une date qui est anterieure dans les textes que tu as fourni. Ce qui comptera ca sera de distinguer les dates des textes futurs.

**Comment by mose** [comment]
Note: je change aussi le lien en haut a droite pour pointer sur la page https://crazy-toads.github.io/cercles/

**Comment by yaminasaheb** [comment]
Oui, STP

**Comment by mose** [comment]
C'est fait, donc je ferme ce ticket.
