### ISSUE TITLE
How to avoid the listing views

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#6]
Mose, 
Serait-il possible de faire apparaître en-dessous de chaque lien un bout du texte avec le mention ''read more'' pour éviter cette vue en listing que nous n'avons dans toutes les rubriques. 
voir exemple 
https://www.openexp.eu/
Merci

**Comment by mose** [comment]
Ca serait possible si on avait un chapeau identifiable, c'est pas le cas pour tous les textes. On peut prendre une nombre de mots arbitraires mais ca risque de faire bizarre dans certains cas.

**Comment by yaminasaheb** [comment]
Pour faire simple prends les deux premières phrases de chaque texte 
Par la suite, on pourra mettre en place une règle de chapeau pour les publications. Je ne pourrais pas gérer ça maintenant avec les 34.

**Comment by mose** [comment]
On peut aussi prendre la `description` comme j'ai fait sur https://crazy-toads.github.io/textes/

Cette description, c'est juste une phrase extraite du texte mais pas toujours la première phrase, j'ai tenté de trouver quelque chose qui porte un sens.

**Comment by yaminasaheb** [comment]
Oui super. Comme ça je pourrais demander aux crapauds de sélectionner la phrase qui leur convient

**Comment by mose** [comment]
Dis-moi si ca va comme ca.

**Comment by yaminasaheb** [comment]
Super. Tu peux faire pareil pour les bios et ce qui est encore dans la rubrique ''textes''
Merci

**Comment by mose** [comment]
Pour les bios on a pas ce champs description, malheureusement, mais je peux en ajouter un et .. improviser pour le contenu.

**Comment by yaminasaheb** [comment]
Oui, STP. 
Il faudra faire la même chose pour la rubrique ''partenaires''

**Comment by mose** [comment]
C'est fait, faudra adapter les champs description snas doute, mais la mise en page est prete.
