### ISSUE TITLE
Rubrique Photos/vidéos

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#7]
Bonjour Mose, 
Pourrais-tu STP créer une rubrique pour les photos/vidéos?  Je ne sais pas si c'est mieux d'avoir une seule rubrique pour les deux avec comme intitulé ''Multimédia'' ou bien d'avoir 2 rubriques séparées, l'une pour les photos et l'autre pour les vidéos. 

Ci-dessous ce que nous avons pour les deux rubriques: 
Fabien, l'un des crapauds, a fait des photos de notre séjour au Treilles. 
Ci-dessous le lien pour les télécharger
https://www.dropbox.com/sh/cdh8mvx2uto2540/AACC1aR99iIY52uOOkrmcg_xa?dl=0 

Pour les vidéos, il y a celle de Thanh au TED
https://www.youtube.com/watch?v=ZV4zuepujSc

Est ce que tu peux faire défiler les photos comme ils le font sur cette page
https://www.photovoltaic-conference.com/

Merci

**Comment by yaminasaheb** [comment]
Pour les photos, merci de donner crédits à Fabien Rouire 
https://www.linkedin.com/in/fabien-rouire-4a621588/?ppe=1

**Comment by yaminasaheb** [comment]
Pour les vidéos, il y a également celles faites par Sandrine aux treilles
Elle a fait une vidéo des travaux et une interview avec chaque crapaud présent. 
Je propose de lier la vidéo de l'interview de chaque crapaud à son profile
Je vais envoyer un email à Sandrine avec toi en copie pour qu'elle t'envoie les vidéos
Merci

**Comment by shelleycavaness** [comment]
Hi Yamina, I think the photos and videos should be integrated into the rest of the website and not in a stand alone rubric. It will make the existing content more exiting and varied for the viewer.

**Comment by yaminasaheb** [comment]
Après réflexion je propose la chose suivant: 
Créer un rubrique calendrier pour qu'on puisse mettre nos events. Les photos et les vidéos correspondent toujours à un événement. 
1-Les photos des Treilles correspondent au Retraite qui a lieu du 03 au 07 Avril 2017. Il faut reprendre la short description utilisée par Mose sur l'ancienne version du site et attacher le CR fait par Thanh sur le séjour aux Treilles
2-La video de Thanh correspond au TEDex du 12/06. Mettre une phrase du style ''Thanh Nghiem fut invitée aux folies bergères pour présenter les crapauds fous'' Je rajouterais du texte dessus samedi. 
Merci

**Comment by shelleycavaness** [comment]
HI Yamina, what do you think about putting Thanh's video with her crapaud page? It would animate the content a bit more. Photos and videos with each toad creator would make the profiles more dynamic. (In my opinion some of them seem a bit flat at the moment). And I dont really want to repeat the video under her profile and somewhere else. It seems a shame not to have it with her profile.

**Comment by yaminasaheb** [comment]
Pour mettre les photos dans les bios des crapauds, il faudra tagger chacune des photos pour savoir qui est qui. Or ça, ce n'est pas faisable d'ici lundi soir. 

Je pense que pour commencer un calendrier des évènements, permettrait de valoriser le travail de Fabien. 

Pour info, sur mon site, les pages ''events'' font partie des pages les plus visitées

Plus tard, on pourra tagger les photos et les mettre aussi sur les pages bio pour celles où des personnes apparaissent seules. Pour les autres, je pense qu'il faudra les laisser dans le défilé de l'event
