### ISSUE TITLE
Rubriques manquantes

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#9]
Mose, 

Par rapport au cahier des charges discuté avec Shelley, il nous manque 2 rubriques: 
1-News
2-Nous rejoindre. 

Avec ça, la site sera prêt pour le lancement
Merci
Yam

**Comment by yaminasaheb** [comment]
Dans la rubrique nous rejoindre. Merci de remplacer par un formulaire de contact, voir exemple ci-dessous
https://www.openexp.eu/contact

**Comment by mose** [comment]
Nous travaillons sur un site statique, il n'y a donc pas possibilité d'avoir un formulaire de contact sans faire appel a un service tiers comme 

- https://formspree.io/
- https://formkeep.com/guides/contact-form-jekyll

mais il y en a beaucoup d'autres.

**Comment by shelleycavaness** [comment]
Hi Mose and Yamina, how about just a simple live link that opens the users email-program/app? (Google mail, Outlook, Mailbird, Thunderbirt etc..... )  I think a simple mail-to hyperlink would would do the trick? it would be a quick simple solution. ;-)

**Comment by yaminasaheb** [comment]
Je préfère la solution d'un lien qui amènerait l'utilisateur directement sur son outlook. 
Merci de faire le nécessaire

**Comment by shelleycavaness** [comment]
We can always publish and address later (but we risk lots of spam issues) For now we have a quick contact form with a redirect to email. This should get us by for the first round.
